train_name: whisper
audio_max_length: 320000 # 20s
text_max_length: 350 # 350
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 16
validate_every_n_batches: 1000
num_devices: 4

model_name: medium
learning_rate: 1.0e-4 
batch_size: 0.6 # 12s (0.6 * audio_max_length)
num_train_steps: 120000
warmup_steps: 5000
gradient_accumulation_steps: 2 # NOTE: need to accumulate due to small batch

monitor: 'val_noisy_en_babble/acc_av' # noisy test set
noise_prob: 1.0
noise_snr_train: 0
noise_fn: '/data/sls/scratch/roudi/datasets/musan/tsv/all/train.tsv'
noise_fn_val: 'noise/babble/lrs3/valid.tsv' # single lrs3 babble mixture
noise_fn_test: 'noise/babble/lrs3/test.tsv' # single lrs3 babble mixture

video_model_ckpt: 'models/mavhubert_only_weights.pt'
freeze_video_model: False # train visual encoder
freeze_video_batch_norm_stats: False 

# lang: multi
lang: multi-all

# mod drop: use av 0.5, a 0.0, v 0.5
prob_use_av: 0.5
prob_use_a: 0.0

pt_ckpt: models/whisper_multi-all_medium.pt
train_id: whisper_multi-all_medium

spec_augment: ""
dropout_rate: 0 

resume_training: False
video_projection_train_only: False
video_projection_separate_lr: ''

# video
use_av_hubert_encoder: True
add_gated_x_attn: 1 # 0 for False, 1 for True
av_fusion: separate 

log_output_dir: "slurm/train_video_slurm"
check_output_dir: "models/checkpoint"


